set nocompatible
" 配置多语言环境,解决中文乱码问题
if has("multi_byte") 
    " UTF-8 编码 
    set encoding=utf-8 
    set termencoding=utf-8 
    set formatoptions+=mM 
    set fencs=utf-8,gbk 
    if v:lang =~? '^/(zh/)/|/(ja/)/|/(ko/)' 
        set ambiwidth=double 
    endif 
    if has("win32") 
        source $VIMRUNTIME/delmenu.vim 
        source $VIMRUNTIME/menu.vim 
        language messages zh_CN.utf-8 
    endif 
else 
    echoerr "Sorry, this version of (g)vim was not compiled with +multi_byte" 
endif

"设置行号
set nu!

"设置主题
colorscheme darkblue 
"colorscheme blue

"解决backspace键失灵
set backspace=indent,eol,start

"不自动换行
set nowrap  

"语法高亮
syntax enable 
syntax on

"设置字体
"set guifont=Mircosoft_YaHei_Mono:h13
set guifont=Consolas:h12
set guifontwide=Microsoft_YaHei_Mono:h12

"自动检测文件类型
filetype on
filetype plugin indent on

"支持taglist
let Tlist_Show_One_File=1 
let Tlist_Exit_OnlyWindow=1

"支持WinManager文件浏览组件
let g:winManagerWindowLayout='FileExplorer|TagList'
nmap wm : WMToggle<cr>

"minibufexpl.vim 多文档编辑
let g:miniBufExplMapCTabSwitchBufs=1 
let g:miniBufExplMapWindowsNavVim=1 
let g:miniBufExplMapWindowNavArrows=1

"支持grep
nnoremap <silent> <F3> :Grep<CR>

"支持h\c切换
nnoremap <silent> <F12> :A<CR>
 
set nocp"设置vim与vi不兼容模式
 
"程序中跳转(需ctags支持)
set tags=tags; 
set autochdir

"支持Qt自动补全
set tags+=G:/Qt/2010.05/qt/include/tags
set tags+=G:/Qt/2010.05/qt/src/tags

"下面一句是当保存时会自动生成tags文件
"au BufWritePost *c,*cpp,*h !ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .
"一下是按 F2 生成tags文件
map <F2> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q . <CR>
let Tlist_Ctags_Cmd = 'ctags'
set tags+=./tags

"自动补全括号
:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {}<ESC>i
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>
:inoremap ' ''<ESC>i
:inoremap " ""<ESC>i

function! ClosePair(char)
	if getline('.')[col('.')-1]==a:char
		return "\<Right>"
	else
		return a:char
	endif
endf

"高亮显示括号
set showmatch

"高亮显示被找到的句子
set hlsearch

"在搜索时，输入的词句是逐字符高亮
set incsearch

"搜索时忽略大小写
set ignorecase

"不要闪烁
set novisualbell
 
"for supertab, added by LiaoLiang Nov28,2008
"let g:SuperTabRetainCompletionType=2
"let g:SuperTabDefaultCompletionType="<C-X><C-O>"

" 状态栏不自动消失
set laststatus=2
" 在状态栏的右下角显示光标位置
set ruler
set statusline=[%F]%y%r%m%*%=[Line:%l/%L,Column:%c][%p%%]

"自动化格式
set formatoptions=tcrqn
" 继承前一行的缩进方式，特别适用于多行注释
set autoindent
"译注:开启新行时使用智能自动缩进
set smartindent
" 使用C样式的缩进
set cindent
" 制表符为4
set tabstop=4
" 统一缩进为4
set softtabstop=4
set shiftwidth=4

"支持OmniCppComplete
"filetype plugin indent on
"set completeopt=menuone,longest,menu
set completeopt=longest,menu
let OmniCpp_DefaultNamespaces = ["std"]
let OmniCpp_NamespaceSearch=1
let OmniCpp_GlobalScopeSearch=1
let OmniCpp_ShowAccess=1
let OmniCpp_ShowPrototypeInAbbr=1
let OmniCpp_MayCompleteDot=1		"当有'.'时自动补全
let OmniCpp_MayCompleteArrow=1		"当有'->'时自动补全
let OmniCpp_MayCompleteScope=1
let OmniCpp_DisplayMode=1
"au CursorMovedl,InsertLeave*if pumvisible() == 0|silent!pclose|endif
"

"F5添加对Qt的编译支持
map <F5> :call CompileRunQt()

func CompileRunQt()
	exec "w"
	if &filetype == "cpp"
		exec "!qmake -project"
		exec "!qmake %<.pro"
		exec "!mingw32-make"
	endif
endfunc










